import React from 'react'


export const metadata = {
    title: 'Blog App',
    description: 'Generated by aam',
  }
export default function RootLayout({children}) {
  return (
    <div>This is blog layout</div>
  )
}
